python -m venv .
bin/pip install -r requirements.txt
sudo mv server.service /etc/systemd/system/
sudo systemctl enable server.service
sudo systemctl start server.service
sudo mv boot_setup.service /etc/systemd/system/
sudo mv boot_setup.timer /etc/systemd/system/
sudo mv run_main.service /etc/systemd/system/
sudo systemctl enable run_main.service
sudo systemctl enable boot_setup.timer
